services:
  swg-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.x64
    environment:
      SWG_SERVER_BITS: "64"
    volumes:
      - swg-work-x64:/swg-main

volumes:
  swg-work-x64:
